"""Generate synthetic transactions as JSONL, to benchmark the ``--fast`` path.

Output matches the shape of ``sample-transactions.json`` (one object per line)
and deliberately spreads values across the validator/fraud/settlement branches:
some unsupported currencies and non-positive amounts (-> rejected), some
high-value / structuring / cross-border / wire txns (-> review/flagged), and
plenty of clean ones (-> settled).

Values are generated by deterministic formulas (no RNG) so a given N always
produces the same file — handy for reproducible benchmarks.

    python generate_load.py -n 1000000 -o load.jsonl
    python integrator.py --fast --input load.jsonl
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any, Iterator

CURRENCIES = ["USD", "EUR", "GBP", "JPY", "CHF", "CAD", "AUD", "PLN", "UAH"]
TYPES = ["wire_transfer", "ach", "card", "sepa"]


def generate(n: int) -> Iterator[dict[str, Any]]:
    for i in range(n):
        # ~3% rejected: every 33rd is an unsupported currency, every 50th negative.
        if i % 50 == 0:
            amount = "-100.00"
            currency = "USD"
        elif i % 33 == 0:
            amount = "500.00"
            currency = "XYZ"  # unsupported -> rejected
        else:
            # Spread 1..60000 so some cross the 10000 (high) and 9800-9999
            # (structuring) thresholds the fraud detector cares about.
            cents = (i * 37) % 6_000_000 + 100
            amount = f"{cents // 100}.{cents % 100:02d}"
            currency = CURRENCIES[i % len(CURRENCIES)]

        hour = i % 24  # some land in the 00:00-05:00 unusual-timing window
        yield {
            "transaction_id": f"TXN{i:09d}",
            "timestamp": f"2026-03-16T{hour:02d}:30:00Z",
            "source_account": f"ACC-{1000 + i % 9000}",
            "destination_account": f"ACC-{2000 + i % 9000}",
            "amount": amount,
            "currency": currency,
            "transaction_type": TYPES[i % len(TYPES)],
            "metadata": {"country": "US" if i % 3 else "GB"},
        }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate synthetic transactions (JSONL)")
    parser.add_argument("-n", "--count", type=int, default=1_000_000, help="number of transactions")
    parser.add_argument("-o", "--output", default="load.jsonl", help="output JSONL path")
    args = parser.parse_args(argv)

    with open(args.output, "w", encoding="utf-8") as fh:
        for txn in generate(args.count):
            fh.write(json.dumps(txn))
            fh.write("\n")

    print(f"wrote {args.count:,} transactions to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
