"""
Regression tests for bug 001 — generated by `unit-test-generator` agent.

Scope: only the changes recorded in context/bugs/001/fix-summary.md.
Each test maps to one finding (F-001 / F-002 / F-003 / F-004 or
security ID). FIRST compliance verified per
skills/unit-tests-FIRST.md.
"""

import os
import sys
import tempfile

import pytest
from fastapi.testclient import TestClient

# Ensure env var is set before importing app (required by post-fix code).
os.environ.setdefault("ADMIN_API_KEY", "test-admin-key")

# Use a fresh temp DB per test session.
TMP_DB = tempfile.NamedTemporaryFile(delete=False, suffix=".db").name
os.environ["TASKS_DB_PATH"] = TMP_DB

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from app import app, get_db  # noqa: E402


@pytest.fixture(autouse=True)
def _reset_db():
    """Truncate tasks before every test → Independent + Repeatable."""
    conn = get_db()
    conn.execute("DELETE FROM tasks")
    conn.commit()
    conn.close()
    yield


@pytest.fixture
def client():
    return TestClient(app)


def _seed(client, n):
    """Helper: create N tasks and return their ids in order."""
    ids = []
    for i in range(n):
        r = client.post("/tasks", json={"title": f"task-{i}"})
        assert r.status_code == 201
        ids.append(r.json()["id"])
    return ids


# ---------- F-001 / Bug #1 — pagination off-by-one ----------

def test_list_tasks_returns_exact_limit(client):
    """Regression: bug-001 / F-001 — `limit=N` must return N rows."""
    _seed(client, 5)
    r = client.get("/tasks?limit=5")
    assert r.status_code == 200
    assert len(r.json()) == 5


def test_list_tasks_respects_smaller_limit(client):
    """Regression: bug-001 / F-001 — `limit=3` from 5 rows returns 3."""
    _seed(client, 5)
    r = client.get("/tasks?limit=3")
    assert r.status_code == 200
    assert len(r.json()) == 3


def test_list_tasks_limit_one_returns_one(client):
    """Regression: bug-001 / F-001 — edge case, `limit=1` returned 0 pre-fix."""
    _seed(client, 3)
    r = client.get("/tasks?limit=1")
    assert r.status_code == 200
    assert len(r.json()) == 1


# ---------- F-002 / Security #1 — SQL Injection ----------

@pytest.mark.parametrize(
    "payload",
    [
        "1 OR 1=1",
        "1; DROP TABLE tasks --",
        "1 UNION SELECT 1,1,1,1",
        "abc",
    ],
)
def test_get_task_rejects_injection(client, payload):
    """Regression: bug-001 / F-002 — non-integer task_id must be 422."""
    _seed(client, 1)
    r = client.get(f"/tasks/{payload}")
    assert r.status_code == 422, (
        f"Expected 422 for payload {payload!r}, got {r.status_code}"
    )


def test_get_task_still_works_for_valid_int(client):
    """Regression: bug-001 / F-002 — fix must not break the happy path."""
    ids = _seed(client, 1)
    r = client.get(f"/tasks/{ids[0]}")
    assert r.status_code == 200
    assert r.json()["id"] == ids[0]


def test_get_task_returns_404_for_missing(client):
    """Regression: bug-001 / F-002 — missing id still returns 404."""
    r = client.get("/tasks/9999")
    assert r.status_code == 404


# ---------- F-003 / Bug #2 — complete_task 404 ----------

def test_complete_task_returns_404_for_missing(client):
    """Regression: bug-001 / F-003 — must return 404 for unknown id."""
    r = client.patch("/tasks/9999/complete")
    assert r.status_code == 404
    assert r.json()["detail"] == "Task not found"


def test_complete_task_succeeds_for_existing(client):
    """Regression: bug-001 / F-003 — fix must not break the happy path."""
    ids = _seed(client, 1)
    r = client.patch(f"/tasks/{ids[0]}/complete")
    assert r.status_code == 200
    assert r.json()["status"] == "completed"
    # And the row is actually flipped:
    follow = client.get(f"/tasks/{ids[0]}")
    assert follow.json()["completed"] is True


# ---------- F-004 / Security #2 — env-based admin key ----------

def test_admin_endpoint_rejects_wrong_key(client):
    """Regression: bug-001 / F-004 — wrong key must be 403."""
    r = client.get("/admin/stats?api_key=wrong")
    assert r.status_code == 403


def test_admin_endpoint_accepts_env_key(client):
    """Regression: bug-001 / F-004 — env-loaded key must work."""
    r = client.get(f"/admin/stats?api_key={os.environ['ADMIN_API_KEY']}")
    assert r.status_code == 200
    body = r.json()
    assert "total" in body
    assert "completed" in body


def test_admin_key_is_not_hardcoded_default(client):
    """Regression: bug-001 / F-004 — the pre-fix hardcoded value must not work."""
    r = client.get(
        "/admin/stats?api_key=supersecret-admin-key-do-not-commit"
    )
    assert r.status_code == 403
