"""
Smoke test that exists before the pipeline runs.
Verifies basic app startup. Comprehensive test coverage will be
generated by the Unit Test Generator agent.
"""

import os
import sys
import tempfile

import pytest
from fastapi.testclient import TestClient

# Use a temp DB so the test does not pollute the dev database.
TMP_DB = tempfile.NamedTemporaryFile(delete=False, suffix=".db").name
os.environ.setdefault("TASKS_DB_PATH", TMP_DB)

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from app import app  # noqa: E402


@pytest.fixture
def client():
    return TestClient(app)


def test_app_starts(client):
    """App must respond to OpenAPI schema request."""
    response = client.get("/openapi.json")
    assert response.status_code == 200
    assert response.json()["info"]["title"] == "Task Tracker"
